### ISSUE TITLE
AttributeError: module 'django_mongoengine' has no attribute 'mongo_auth'

### ISSUE THREAD

**Issue by ArseniyBars** [MongoEngine/django-mongoengine#104]
I need to replace depricated `mongoengine.django.auth`  with something working to authorize in my django project. I tried to use mongo_auth in django-mongoengine, but cannot find a way to reach it. May someone explain me, how to reach auth module from `mongoengine.django.auth` inside `django-mongoengine`?
P. S. Is there any documentation or example, explaining how to authorize user, using mongo_auth?

**Comment by last-partizan** [comment]
take a look at https://github.com/MongoEngine/django-mongoengine/tree/master/example/tumblelog

and make sure you using git version of the django-mongoengine module
