### ISSUE TITLE
AttributeError: 'User' object has no attribute '_initialised'

### ISSUE THREAD

**Issue by iemektar** [MongoEngine/django-mongoengine#107]
When I'm creating new user via inherit from MongoUser , i'm taking this error;

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\NGPS\env\lib\site-packages\django\db\models\base.py", line 558, in __init__
    _setattr(self, field.attname, val)
  File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\NGPS\env\lib\site-packages\mongoengine-0.14.3-py3.6.egg\mongoengine\base\fields.py", line 144, in __set__
    if instance._initialised:
AttributeError: 'User' object has no attribute '_initialised'

models.py
__________________________________________
from django_mongoengine.mongo_auth.models import MongoUser
from django_mongoengine import fields

class User(MongoUser):
    username = fields.StringField()
    password = fields.StringField()
    first_name = fields.StringField()
    last_name = fields.StringField()
    is_superuser = fields.BooleanField()

    def __str__(self):
        self.username
______
I tried creating in the shell by this codes;

from user.models import User
new_user = User(username='testuser',password='test_pass', first_name='test',last_name='user',is_superuser=True).save()

**Comment by last-partizan** [comment]
take a look at mongo_auth.models

there is working example
