### ISSUE TITLE
Django 2.0

### ISSUE THREAD

**Issue by JWDobken** [MongoEngine/django-mongoengine#109]
does anyone know how to configure mongodb engine for the new release Django v2.0?

**Comment by last-partizan** [comment]
Same as always https://github.com/MongoEngine/django-mongoengine#connecting.
But it not tested yet, probably something can be broken.

**Comment by rrmerugu** [comment]
@JWDobken is this working with Django 2.0

**Comment by nagsamayam** [comment]
Hi @JWDobken,  its working with Django 2.0. To configure Mongodb, please follow like mentioned below.

# settings.py
from mongoengine import *

'django_mongoengine', # Add this line to installed app

# Mongo DB configuration

MONGODB_DATABASES = {
    "default": {
        "name": '<db_name>',
        "host": 'localhost',
        "password": '',
        "username": '<username>',
        "tz_aware": True, # if you using timezones in django (USE_TZ = True)
    },
}

**Comment by rrmerugu** [comment]
@nagsamayam thanks for the update

**Comment by Rakin061** [comment]
@JWDobken 

How did you installed django-mongoengine package for Django 2.0 ? I can't install using pip for Django 2.0.7 ?

**Comment by last-partizan** [comment]
@Rakin061 
```
pip install -e git+https://github.com/MongoEngine/django-mongoengine.git#egg=django-mongoengine
...
Successfully installed django-2.0.7 django-mongoengine mongoengine-0.15.3 pymongo-3.7.1 pytz-2018.5 six-1.11.0

```

**Comment by Rakin061** [comment]
@last-partizan 

Thanks.. it works!! But I can't import `mongo_admin` or any files from the djanog-mongoengine package. I am using windows and can't find any package in the site-packages.
