### ISSUE TITLE
    super(StringField, self).__init__(**kwargs) TypeError: __init__() got an unexpected keyword argument 'auto_created'  on 3.4, but you're tryin

### ISSUE THREAD

**Issue by satyamtripathi11** [MongoEngine/django-mongoengine#112]
Using Django 1.11, settings.py is taken from the given example. All the requirements have been taken care of.

**Comment by last-partizan** [comment]
Can you provide full traceback please?

**Comment by satyamtripathi11** [comment]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\utils\autoreload.py", line 227, in
wrapper
    fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\core\management\commands\runserver.
py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "C:\Python27\lib\site-packages\django\utils\autoreload.py", line 250, in
raise_last_exception
    six.reraise(*_exception)
  File "C:\Python27\lib\site-packages\django\utils\autoreload.py", line 227, in
wrapper
    fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Python27\lib\site-packages\django\apps\registry.py", line 108, in pop
ulate
    app_config.import_models()
  File "C:\Python27\lib\site-packages\django\apps\config.py", line 202, in impor
t_models
    self.models_module = import_module(models_module_name)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Python27\lib\site-packages\django_mongoengine-0.3-py2.7.egg\django_mo
ngoengine\mongo_auth\models.py", line 52, in <module>
    class ContentType(document.Document):
  File "C:\Python27\lib\site-packages\django_mongoengine-0.3-py2.7.egg\django_mo
ngoengine\mongo_auth\models.py", line 53, in ContentType
    name = fields.StringField(max_length=100)
  File "C:\Python27\lib\site-packages\django_mongoengine-0.3-py2.7.egg\django_mo
ngoengine\fields\djangoflavor.py", line 32, in __init__
    super(DjangoField, self).__init__(*args, **kwargs)
  File "C:\Python27\lib\site-packages\mongoengine\fields.py", line 63, in __init
__
    super(StringField, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'auto_created'

**Comment by last-partizan** [comment]
What version of mongoengine are you using? i cannot reproduce this with 0.14.3 or 0.15.0

**Comment by satyamtripathi11** [comment]
The issue got solved by upgrading mongoengine version.
Thanks.
I have another issue now, I have to use login for my app, I have used the default User model from django_mongoengine.mongo_auth.models . I am importing login,logout and authenticate from django.contrib.auth. It is successfully authenticating the user but cannot login. It is giving None when trying to login.

**Comment by last-partizan** [comment]
Take a look at example app, i remember login was working.

**Comment by satyamtripathi11** [comment]
There isn't an implementation of login inside the example.

**Comment by last-partizan** [comment]
Oh, probably it was login inside django-admin.

Show me your login code and traceback.

**Comment by satyamtripathi11** [comment]
@csrf_exempt
def log_in(request):
    users = User.objects.all()
    print users
    for user in users:
      print user.username
      print user.password
    for key, value in request.GET.iteritems():
      #print "%s %s" % (key, value)
      if key == 'username':
        username = value
      if key == 'password':
        password = value

    try:
        user = User.objects.get(username=username)
        if user.check_password(password):
            print "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
           # user.backend = 'mongoengine.django.auth.MongoEngineBackend'
            user = authenticate(username=username, password=password)
            print authenticate(username=username, password=password)
            print login(request, user)
            login(request, user)
            print "logged in"
            request.session.set_expiry(60 * 60 * 1) # 1 hour timeout
            return HttpResponse(login(request, user))
        else:
            return HttpResponse('login failed')
    except DoesNotExist:
        return HttpResponse('user does not exist')
    except Exception,e:
        # Get line
        logger = logging.getLogger('django.request')
        logger.exception(unicode(e))
      
        return HttpResponse(logger.exception(unicode(e)))
There is no error, but for the final Response(return HttpResponse(login(request, user))) I am getting None

**Comment by last-partizan** [comment]
Are you using django.contrib.auth.login?
it does not return anything; Take a look at `django.contrib.auth.views.LoginView` for example usage.

**Comment by satyamtripathi11** [comment]
django.contrib.auth.views.LoginView uses django.contrib.auth.login for login which I am using too.
The authentication is going on correctly but login returns None.

**Comment by satyamtripathi11** [comment]
Already using AUTH_USER_MODEL = 'mongo_auth.MongoUser' in settings.py

**Comment by last-partizan** [comment]
`login` should return None. it's okay, you must redirect use somewhere else if you want to.

**Comment by last-partizan** [comment]
here is example from django code.
```
        """Security check complete. Log the user in."""
        auth_login(self.request, form.get_user())
        return HttpResponseRedirect(self.get_success_url())
```

auth_login is your login, as i understand.

**Comment by satyamtripathi11** [comment]
okay thanks, one more thing, where will the user information be stored(tokens and otherwise)(I have used the default User model)?

**Comment by last-partizan** [comment]
`login` stores SESSION_KEY in request.session

and if you configured SESSION_ENGINE = 'django_mongoengine.sessions' it will be stored in django_session collection.

**Comment by satyamtripathi11** [comment]
Yes, got it. Thanks.
