### ISSUE TITLE
How do you refer User model

### ISSUE THREAD

**Issue by erdenezul** [MongoEngine/django-mongoengine#114]
<pre>
from django_mongoengine.mongo_auth.models import MongoUser
from django_mongoengine import Document, fields

class Profile(Document):
     # version 1
     user = fields.ReferenceField(Mongouser)
     # it will give Argument to ReferenceField constructor must be a document class or a string
     # version2
     user=fields.ReferenceField('MongoUser')
     # it will give MongoUser has not been registered
</pre>

**Comment by last-partizan** [comment]
maybe try 'mongo_auth.MongoUser'

**Comment by erdenezul** [comment]
<pre>
from django_mongoengine.mongo_auth.models import MongoUser

type(MongoUser)
out[3]: django.db.models.base.ModelBase

</pre>

**Comment by last-partizan** [comment]
How about 'mongo_auth.User'? :)

Actually, if you're starting new project and using python3, maybe try  https://nesdis.github.io/djongo/ instead of this project. I have not used it yet, but it looks like mongo support done right (using db backend and not dirty hacks)
