### ISSUE TITLE
admin panel error

### ISSUE THREAD

**Issue by devtrk** [MongoEngine/django-mongoengine#116]
I want to delete the record from the admin panel.
 
I get this error:

> 'ObjectIdField' object has no attribute 'auto_created'

what should I do?

Thank you

**Comment by last-partizan** [comment]
Hi, this project is not really active. You can try to dig into django-mongoengine yourself and fix it.
Or maybe if you're starting new project, try to use https://nesdis.github.io/djongo/, probably it will work better.

**Comment by liwancheng91** [comment]
@devtrk    
 I have the same problem,  my solution is :
add auto_created as property to fields/__init__.py patch_mongoengine_field 

	def patch_mongoengine_field(field_name):
	    """
	    patch mongoengine.[field_name] for comparison support
	    becouse it's required in django.forms.models.fields_for_model
	    importing using mongoengine internal import cache
	    """
	    from mongoengine import common
	    field = common._import_class(field_name)
	    for k in ["__eq__", "__lt__", "__hash__", "attname", ]:
	        if k not in field.__dict__:
	            setattr(field, k, djangoflavor.DjangoField.__dict__[k])
	    # set auto_created False for check in django db model when delete
	    if field_name == "ObjectIdField":
	        setattr(field, "auto_created", False)
    
- see also:
  [django-mongoengine#95](https://github.com/MongoEngine/django-mongoengine/issues/95)

**Comment by last-partizan** [comment]
I included this fix into master.
