### ISSUE TITLE
Performing raw queries on mongo database

### ISSUE THREAD

**Issue by luvpreetsingh** [MongoEngine/django-mongoengine#117]
Hi, I know this project is not being maintained, but still.....

Like in Relational Databases, django gives us option to perform raw sql queries on the database.

https://docs.djangoproject.com/en/2.0/topics/db/sql/

You can get connection object to database via by
 
    from django.db import connection

And then you can perform raw sql queries via this connection object.

Is there any way I can do this on mongo database while using mongoengine?

This is the way I am connecting in settings.py,

    mongoengine.connect(host='xx.xxx.xx.xx.xx.xx.xx.xx.xxx.xx.')

**Comment by luvpreetsingh** [comment]
Hi, I got it. Never mind. 

    mongoengine.connection.get_connection()

**Comment by last-partizan** [comment]
:+1:
