### ISSUE TITLE
Production ready release??

### ISSUE THREAD

**Issue by pratibhajagnere** [MongoEngine/django-mongoengine#118]
Hi,

I am using mongoengine in my Django app and I want to consume Django 2.0

I need to know if we are planning to have mongoengine production ready in next couple of months or if we have any target date set for it.

**Comment by last-partizan** [comment]
Hello.

I have plans to update my project to django 2.0, and right now django-mongoengine passing tests with django 2.0.

But i don't think this project is ready to public release. It's codebase old and consists of strange monkey-patches and magick.

You can try to use it and improve what you need. Or try to use https://nesdis.github.io/djongo/ it looks better, but i haven't touched it yet.

**Comment by pratibhajagnere** [comment]
@last-partizan I was also thinking of trying Djongo but that is also not production ready yet.

**Comment by last-partizan** [comment]
If you think django-mongoengine is better option and have time to make it production ready for you, i'll accept pull requests.

Right now i'm using this 'not-so-production-ready' version in production, and it works well. We don't use admin interface, so there can be bugs. But models and forms works fine.

But i hope to try djondo, when we migrate to py3. What problems did you found with djondo? or maybe some discussion of it's production-readinness?

**Comment by farhan0581** [comment]
I had fixed some issues and was able to use admin interface with Django 1.11
Though it needs improvement, I will try to give a pull request as soon as I am back to work.

**Comment by kiorq** [comment]
Can you make a list of what you think needs to be improved? So other developers can start tackling them? I will be glad to help and i'm sure others would be too.

**Comment by last-partizan** [comment]
@kiorq here is list
https://github.com/MongoEngine/django-mongoengine#working--django-111

**Comment by last-partizan** [comment]
@farhan0581 we're waiting for pull-request ;)

**Comment by last-partizan** [comment]
@kiorq if you want to help - test admin interface using example app, and extend readme on what works/doesn't.
auth/Users/Contenttypes may be also somewhat bugged, becouse i don't use it in production.

**Comment by farhan0581** [comment]
I have raised a pull request. Please check.

**Comment by last-partizan** [comment]
@farhan0581 thanks, looks fine, merged it.
