### ISSUE TITLE
TypeError: '<' not supported between instances of 'ListField' and 'StringField' ??

### ISSUE THREAD

**Issue by antonio-irarrazaval** [MongoEngine/django-mongoengine#126]
Hi !

 I have a Document:

```
class Cuestionario(Document):
    nombre = fields.StringField(max_length=20)
    tagline = fields.StringField(default="vacio")
    fadis: [Fadi] = fields.ListField(fields.EmbeddedDocumentField(Fadi))

    def __str__(self):
        return f"cuestionario: {self.nombre}"

    meta = {
        'collection': 'cuestionario',
        'strict': False
    }

```

 then, make the Form  :
```
class CuestionarioForm(DocumentForm):

    class Meta:
        document = Cuestionario
        fields = '__all__'
        # exclude = ('fadis',)
```
But, when start the runserver, fails :

![image](https://user-images.githubusercontent.com/49562616/56082055-210cf480-5de2-11e9-83a8-57fc369dbfcc.png)

_requirements.txt:
```
Django==2.2
django-bootstrap3==11.0.0
django-mongoengine==0.3.1
mongoengine==0.17.0
Pillow==6.0.0
pymongo==3.7.2
pytz==2018.9
six==1.12.0
sqlparse==0.3.0
```

python version:
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] 

Any Ideas?

**Comment by last-partizan** [comment]
Hi, no idea really.

We have very similar case in example/tumplelog app, but it works without issues.

**Comment by antonio-irarrazaval** [comment]
Hi, 
      after some debug, the problem raises in **sorted** function... they don't know how to sort StringFields and ListFields... in django_mongoengine/forms/documents.py 
indeed:

![image](https://user-images.githubusercontent.com/49562616/56093615-e7e38b80-5e98-11e9-8d28-bc1e04a7e2b9.png)

With a little monkeypatch in mongoengine/base/fields.py , added at the end of the BaseField(object) simple:

```
    def __lt__(self, other):
        return self.name < other.name

```

![image](https://user-images.githubusercontent.com/49562616/56093677-a6071500-5e99-11e9-9187-64a5744a4214.png)


and works like a charm....

Best regards...

**Comment by last-partizan** [comment]
@antonio-irarrazaval hey, by the way, are you using `mongoengine.fields` and not `django_mongoengine.fields`?

Becouse we have this monleypatch already.
