### ISSUE TITLE
Too slow with >1K documents!

### ISSUE THREAD

**Issue by mosynaq** [MongoEngine/django-mongoengine#138]
I used this ORM in my project. My MongoDB instance has approximately 158,000 documents which are nothing for a big data database. When I try to retrieve the first 100 documents, I have to wait for **more than 2 minutes**!
I have 3 Document models and 19 EmbeddedDocument models. I can retrieve documents as fast as expected (about 0.01 seconds) when using vanilla Mongoengine.
What is the problem?

**Comment by last-partizan** [comment]
How do you try to retrieve it if first and second cases?

**Comment by mosynaq** [comment]
Found the problem: I was using Django's default pagination and it counts the number of the records after filtering model. This made the retrieval process slow. Switching to cursor-based pagination did the job.
Closing the issue.
