### ISSUE TITLE
Toolbar issue

### ISSUE THREAD

**Issue by rozza** [MongoEngine/django-mongoengine#14]
I apologize if this is the wrong group for this bug report-- this was the only place where I could find discussion of a django-debug-toolbar-mongo bug.

I ran into a problem with the django debug toolbar because operation_tracker's _update (and insert and remove) method specifies the deprecated "safe" option, with a default value of False. Not only is the option deprecated, but if it is not specified at all, mongo uses a default value of None, which ultimately gets transformed into True. The safe property has been replaced by WriteConcern.

Our application had defined a WriteConcern of 1 at the collection level, but it was getting overriden on individual calls by the debug toolbar's safe=False option. I had to explicitly pass w=1 on each insert, update, and remove call.

This bug exists with the most recent version, 1.9.

Thanks,

Christina Roberts

**Comment by last-partizan** [comment]
Django-toolbar support is removed from this project; Here is another https://github.com/hmarr/django-debug-toolbar-mongo
Hope it works. Closing issue.
