### ISSUE TITLE
mongo-admin from django_mongoengine not supporting FieldList. Throwing ValidationError for list

### ISSUE THREAD

**Issue by nidhishah989** [MongoEngine/django-mongoengine#152]
Error:::   ValidationError (ArtWorks:None) (Only lists and tuples may be used in a list field: ['tags'])
----------------------------------------------------------------------------------------------------------------------
I am receiving this error, How to add listfield values from mongo-admin, not the Django admin. Please help.
----------------------------------------------------------------------------------------------------------------------------
my Models.py
from django_mongoengine import Document, fields
#from mongoengine import *
class ArtWorks(Document):
    artname=fields.StringField(blank=False, max_length=200)
    description=fields.StringField(max_length=700)
    artType = (
        ('Acrylic', 'Acrylic Painting'),
        ('WaterColor', 'WaterColor Painting'),
        ('fabric', 'fabric Painting')
       )
    paintingTpye =fields.StringField(max_length=30,choices=artType,default='Acrylic')
    artCategory=(
        ('landscape','Landscape Painting'),
        ('still life','Still Life Painting'),
        ('portrait', 'Portrait Painting'),
        ('Religious','Religious Painting'),
        ('flower', 'Flower painting'),
        ('Animal','Animal Painting'),
        ('bird', 'bird Painting')
    )
    paintingCategory = fields.StringField(max_length=30,choices=artCategory,default='landscape')
    priceUSA= fields.DecimalField(min_value=0,max_digits=6,precision=2)
    wishCount= fields.IntField(min_value=0)
    avialable= fields.BooleanField()
    tags = fields.ListField(fields.StringField(max_length=30))

    def __str__(self):
        return self.artname
------------------------------------------------------------------------------------------------------------------------------
my admin.py file
from django_mongoengine import mongo_admin as admin

from store.models import ArtWorks

# Register your models here.

@admin.register(ArtWorks)
class ArtWorksAdmin(admin.DocumentAdmin):
    pass
---------------------------------------------------------------------------------------------------------------------------------
I would like to make tags for one painting as a list , so I can do search query for paintings using tags.
I am using mongoengine admin interface to add values to the collection of artwork. However, ListField is throwing validation error. I am sure, that the form is not supplying the value as a list. I try all possible values. Can't resolve this. If I would like to give the admin page to an artist so she can add her paintings. How I can provide her tag field so, she can add as many tags for her paintings which will store as a list in the database?
Thank you in advance.

**Comment by last-partizan** [comment]
ListField is not supported at the moment.

You could write your own widget for admin, using `django.contrib.postgres.fields.array.SimpleArrayField` as example.

When it works, you could add support for this field to django-mongoengine by creating PR.

**Comment by nidhishah989** [comment]
How I can find which fields are supported for admin page? I am new to django and mongoengine and trying to understand how this works for CRUD operation.
I am trying to create a web application with django with mongoengine. I downloaded the example/tumblelog project from master branch for reference. In that project also, I cannot add values for comments. Same validation problem comes. 
Thank you in advance.

**Comment by last-partizan** [comment]
You test if it works - it works.

If you're new to django and mongoengine, you should try using postgres, instead of mongoengine. It will be better expirience, and more things will work out of the box.
