### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by pythonhubpy** [MongoEngine/django-mongoengine#155]
It seems like in the website it has been mentioned this package is coming soon. And even I don't see any awaiting pr's for this repo and also the latest commit was on November 2021. So is this package still maintained and can we use it with the latest version of Django. Or is there any plans to release a major version?

**Comment by last-partizan** [comment]
Hi.

The project is in maintenance mode, and i don't expect any improvements or major releases.

It is compatible with django 3.2, but i would not recomment using it for any new projects.
