### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured

### ISSUE THREAD

**Issue by krishna-bhandari** [MongoEngine/django-mongoengine#165]
How to solve the following error?

`raise ImproperlyConfigured("settings.DATABASES is improperly configured. "
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.`

I am getting this error while migrating DB.

My DB setting according to docs in this package is:
`
MONGODB_DATABASES = {
    "default": {
        "name": 'nft_db',
        "host": 'localhost',
        "password": '',
        "username": '',
        "tz_aware": True, # if you using timezones in django (USE_TZ = True)
    },
}`

**Comment by last-partizan** [comment]
```
DATABASES = {'default': {'ENGINE': 'django.db.backends.dummy'}}
```

That's django telling you that you haven't configured database.
