### ISSUE TITLE
ImproperlyConfigured: settings.DATABASES is improperly configured.

### ISSUE THREAD

**Issue by dannyroa** [MongoEngine/django-mongoengine#21]
I set settings.DATABASES to 

{
    'default': {
        'ENGINE': 'django.db.backends.dummy'
    }
}

I'm still getting

ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.

I'm on Django 1.6.2.

**Comment by last-partizan** [comment]
when you set django database engine to 'django.db.backends.dummy' it's supposed to throw that error when something accessing db;

closing issue.

**Comment by yoanisgil** [comment]
I'm facing the same issue. My DATABASES settings looks like this:

```python
DATABASES = {
    'default': {'ENGINE': 'django.db.backends.dummy'}
}
```

which I got from [here](https://github.com/MongoEngine/django-mongoengine/blob/master/example/tumblelog/tumblelog/settings.py#L25)

@last-partizan if the engine is not set to 'django.db.backends.dummy' then what it should be set to? Also, I was wondering if the project is supposed to support migrations?

Below my *requirements.txt*:

```
Django==1.8
django-rest-swagger==0.3.4
djangorestframework==3.3.0
mysqlclient==1.3.7
PyYAML==3.11
wheel==0.24.0
gunicorn==19.3.0
rest_condition==1.0.2
virtualenvwrapper==4.7.1
PyJWT==1.4.0
django-jenkins==0.18.1
coverage==4.0.3
pep8==1.6.2
pyflakes==1.0.0
mongoengine==0.10.0
django-rest-framework-mongoengine==3.3.0
-e git://github.com/MongoEngine/django-mongoengine.git#egg=django-mongoengine
```

**Comment by last-partizan** [comment]
Original error is raised by django when it's using something that needs db access.
You can configure it to whatever you want. If you need another db with migrations - just configure it like always.

**Comment by rubenalvesbcn** [comment]
Hi all

I'm having the same problem.

I'm using Django REST Framework, Mongoengine and Django REST Framework Mongoengine

It's clear that the exception is raised because the settings.DATABASES is not set, once when using mongoengine, this is not required.

How should we proceed? Use a MySQL to authentication and Mongoengine to anything else? I really don't know how to proceed.

**Comment by last-partizan** [comment]
Probably yes, it's better to use mysql or postgres for basic django parts like auth/contenttypes, and mongo for anything else.

**Comment by rubenalvesbcn** [comment]
Hm

I think that using two different databases on the same application is not a "good practice", but it seems that is the only option if we want the power of Django REST Framework and Mongoengine together.

**Comment by tan234** [comment]
python manage.py makemigrations
python manage.py migrate
