### ISSUE TITLE
ObjectId('55d3f4b756c02c3f3a0febc1') is not JSON serializable

### ISSUE THREAD

**Issue by pang-w** [MongoEngine/django-mongoengine#26]
vagrant@precise64:~/wwwroot/xxxx$ django-admin --version
    1.7.8
    In [3]: mongoengine.VERSION
    Out[3]: (0, 10, 0)
    In [5]: pymongo.version
    Out[5]: '3.0.3'

Setting file error:

    MONGODB_DATABASES = {
            'default': {'name': 'XXX'}
    }
    AUTHENTICATION_BACKENDS = (
        'django_mongoengine.auth.backends.MongoEngineBackend',
    )
    SESSION_ENGINE = 'django_mongoengine.sessions'
    # SESSION_SERIALIZER = 'django_mongoengine.sessions.BSONSerializer'

User login error

    TypeError at /login/
    ObjectId('55d3f4b756c02c3f3a0febc1') is not JSON serializable
    Request Method:	POST
    Request URL:	http://192.168.33.10:8888/login/?next=/loginout/
    Django Version:	1.7.8
    Exception Type:	TypeError
    Exception Value:	
    ObjectId('55d3f4b756c02c3f3a0febc1') is not JSON serializable
    Exception Location:	/usr/lib/python2.7/json/encoder.py in default, line 184
    Python Executable:	/usr/bin/python
    Python Version:	2.7.6

Fix this error, Setting file:

    MONGODB_DATABASES = {
            'default': {'name': 'XXXXX'}
    }
    AUTHENTICATION_BACKENDS = (
        'django_mongoengine.auth.backends.MongoEngineBackend',
    )
    SESSION_ENGINE = 'django_mongoengine.sessions'
    SESSION_SERIALIZER = 'django_mongoengine.sessions.BSONSerializer'

but new django_mongoengine not found `django_mongoengine.sessions.BSONSerializer`,  Add code to django_mongoengine/sessions.py

    from bson import json_util

    class BSONSerializer(object):
        """
        Serializer that can handle BSON types (eg ObjectId).
        """
        def dumps(self, obj):
            return json_util.dumps(obj, separators=(',', ':')).encode('ascii')

        def loads(self, data):
            return json_util.loads(data.decode('ascii'))

Why do you want to delete BSONSerializer?
Please check your code to include the example/tumblelog.

**Comment by last-partizan** [comment]
I've restored content of sessions.py from latest working mongoengine release.
Now this error is fixed.
