### ISSUE TITLE
Which django version will be supported

### ISSUE THREAD

**Issue by ipfans** [MongoEngine/django-mongoengine#36]
There is few different between django versions. So whice django version this module will support？

So if you didn't mind, I want to do some contribution for this module.

**Comment by ebar0n** [comment]
I'm trying to use this module, but many things are broken Django 1.9, I think it should be given always support the latest version of Django, careful use of Python 2 and Python 3

**Comment by ipfans** [comment]
@ebar0n this module is broken long time ago, so you should not use this module unless it's stable.

**Comment by ipfans** [comment]
I suggest to work with https://www.djangoproject.com/download/#supported-versions support django>=1.8.

**Comment by last-partizan** [comment]
You're correct, we should support latest django versions.
And python >=2.7
https://docs.djangoproject.com/en/1.9/faq/install/#what-python-version-can-i-use-with-django

**Comment by ipfans** [comment]
@last-partizan So can I have your email to communicate with more details? my email: ipfanscn <at> gmail dot com

**Comment by ebar0n** [comment]
@ipfans Only've been testing this module are broken many things for the admin etc. but the basic operation for the models remains compatible, in my opinion I think I'll use it and so I force you to correct errors in its path. This module seems the best alternative :)
