### ISSUE TITLE
do this have a proposed release date  !!

### ISSUE THREAD

**Issue by rrmerugu** [MongoEngine/django-mongoengine#38]
Hello guys, I love mongoengine  and been using it for a while, but recently you stopped support for django . Im ok to use 0.9 version, but some how i could not use pymongo 3.2 and latest drf versions because of mongoengine 0.9. 

Im glad that you guys are working on this .. So when can we expect the support back

**Comment by last-partizan** [comment]
We don't have a release date, but you can try to use git version, and help to fix something that doesn't work for you.

**Comment by rrmerugu** [comment]
cool.. thanks..

**Comment by bailu0404** [comment]
guys, hope everything going well. we do desperately need a stable version. Please keep working on this!! we'll buy you guys beer in return :+1:

**Comment by Alex131089** [comment]
Is https://github.com/MongoEngine/django-mongoengine/blob/master/README.rst up to date ?
I'm new to django (but familiar with python scripting), I'm starting a project not very complicated, can I expect this to works for basic features ?

**Comment by last-partizan** [comment]
@Alex131089 Readme is up-to-date, i just added line "models/fields" to working features.

Try to use this project and see if everything you need is working.
