### ISSUE TITLE
update "type", "size" fields of Document ERROR

### ISSUE THREAD

**Issue by yanheven** [MongoEngine/django-mongoengine#39]
in one of my Document, there is two fields "type" and "size", update it as follow:
body = {'type': 'test4'}
customers = Customer.objects(name='test').update_one(**body)

error raised:
    customers = Customer.objects(name='test').update_one(**body)
  File "/home/evan/code/hp/RESMGMT/rm_project/.tox/py34/lib/python3.4/site-packages/mongoengine/queryset/base.py", line 516, in update_one
    upsert=upsert, multi=False, write_concern=write_concern, **update)
  File "/home/evan/code/hp/RESMGMT/rm_project/.tox/py34/lib/python3.4/site-packages/mongoengine/queryset/base.py", line 450, in update
    update = transform.update(queryset._document, **update)
  File "/home/evan/code/hp/RESMGMT/rm_project/.tox/py34/lib/python3.4/site-packages/mongoengine/queryset/transform.py", line 246, in update
    field = cleaned_fields[-1]
IndexError: list index out of range

and I tracee it, found that both "type" and "size" is COMPARISON_OPERATORS keyword in file  /mongoengine/queryset/transform.py

how can I update  "type" and "size" fields of my Document?

**Comment by last-partizan** [comment]
Hello, yeah i tested it and it doesn't work. But i can do nothing here, querysets handled by mongoengine package, not django-mongoengine.

So, report it here: https://github.com/MongoEngine/mongoengine/issues

**Comment by ipfans** [comment]
It relates to https://github.com/MongoEngine/mongoengine/issues/1194 and https://github.com/MongoEngine/mongoengine/issues/244 

But if you like you can try this way:

```
class Customer(Document):
    name = StringField(required=True)
    type = StringField(default="")

if __name__ == '__main__':
    c = Customer()
    c.name = "Joe"
    c.save()
    body = {'type': 'test4'}
    n = Customer.objects(name="Joe").first()
    for key in body.keys():
        n.__setattr__(key, body[key])
    n.save()
    c = Customer.objects(name="Joe").first()
    print c.type
```

**Comment by yanheven** [comment]
thanks @last-partizan and @ipfans , it should be issue of mongoengine, not django-mongoengine.
and the idea of @ipfans is good

**Comment by yanheven** [comment]
@ipfans 's solution is not an atomic update.
