### ISSUE TITLE
Using applications relying on django models

### ISSUE THREAD

**Issue by mwjackson** [MongoEngine/django-mongoengine#50]
Any ideas for approaches on using apps relying on django models? I was thinking something along the lines of monkey patching the models & replacing the relevant parts (eg. TextField => StringField), but I noticed you've been re-implementing them in this project (eg. the django auth).

What lessons have you learned so far and what do you think the best approach might be?

**Comment by last-partizan** [comment]
What i learned: someone who decided to rewrite django.auth was crazy, django updated - everything broken (almost) and maybe monkey-patching was better idea.

Right now i try to monkey-patch everything with minimal rewriting. And your approach might be different depends on what apps you want yo use.

**Comment by mwjackson** [comment]
Well, we have a bunch of apps that we use such as django-allauth, django-organizations, user_sessions. I guess its not realistic to submit PR's to all of those libraries with mongoengine support, so the only alternative is to monkey patch them (or django's model system). 

You said you were monkey patching everything, do you have any code that I could use as a starting point?

**Comment by last-partizan** [comment]
Basically i import django module, and then replace something not working with a fix using this: https://github.com/MongoEngine/django-mongoengine/search?utf8=%E2%9C%93&q=get_patched_django_module

But if don't think it's good idea to patch every app. Maybe you should take a look at django-mongodb-engine and django-nonrel.

**Comment by mwjackson** [comment]
We're currently using django-nonrel, which is no longer maintained (django 1.6 is the last release), hence why I'm looking at django-mongoengine.

I'll take a look at your code and see if there is a nice seam somewhere.

**Comment by mwjackson** [comment]
Did you investigate writing your own django db backend (similar to nonrel/mongodb-engine) that just maps to mongoengine queries?

**Comment by last-partizan** [comment]
I was thinking about it, that's bad idea - mongodb is different from relational databases, so not every query has a match. Probably - it will work for some simple cases, but can not ever transparent replace db layer for app written for relational db.

**Comment by mwjackson** [comment]
That's absolutely true. In practice this is how django-nonrel does it (plus ListField & DictField), and it seems to work quite well as long as long as you can do without the parts that don't match such as some aggregations. 

I looked at the monkey patching route and its not really workable (and not generally a nice idea for client apps as you suggested) so I don't know where to go now. Our options are

a) help with django-mongoengine and figure out some solution to integrating client applications, probably via a db backend.
b) fork nonrel and try to bring it up to date with django 1.9

Thoughts? Are you interested in a)?

**Comment by last-partizan** [comment]
db backend way requires heavy django patching. becouse if it does not, there would be only django-mongodb-engine

Maybe you can try to replace some modules with mongo-supported ones? like, sessions from this project.

I'm interested in everything that includes making django_mongoengine better, but i don't have much time to do it myself. So patches and pull-requests are welcome.
