### ISSUE TITLE
PyPI release? 

### ISSUE THREAD

**Issue by apolkosnik** [MongoEngine/django-mongoengine#52]
There seems to be 0.01 on PyPI, any chance of getting the more recent version out?

Thanks!

**Comment by Jcbobo88** [comment]
:+1:

**Comment by last-partizan** [comment]
Unfortunately, package is not ready for release yet, you can install from github if you want to use non-stable version.

**Comment by dblado** [comment]
@last-partizan Github release is 0.3.1 -- could you release to PyPi now?

**Comment by last-partizan** [comment]
@dblado Probably yes.

Right now i don't have access to pypi but i just emailed @rozza and we will find a way to do release.

**Comment by last-partizan** [comment]
Released.
