### ISSUE TITLE
Unable to save empty list on a EmbeddedDocumentListField

### ISSUE THREAD

**Issue by saraht129** [MongoEngine/django-mongoengine#54]
I have models declaration as below:

    class Tag (EmbeddedDocument):
        tag_object: fields.StringField(required=True)
        tag_line: fields.StringField(required=True)

    class TagEntry (Document):
        email = fields.EmailField(required=True)
        tags = fields.EmbeddedDocumentListField(Tag, required=False)

Whenever I try to do:

     tag_entry.tags = []
     tag_entry.save()

I get a ValidationError like below:

    ValidationError (TagEntry:56ffa40ee72569659e273281) (Field is required and cannot be empty: ['tags'])

What is wrong here?

**Comment by last-partizan** [comment]
We're using django-like `blank=True, null=True`, and then setting `required = not blank`.
So, your required=False gets ignored here.

What do you think we chould raise error if user using `required` or setting blank/null from `required`?

**Comment by saraht129** [comment]
Thanks, didn't realise the different parameters there, did I miss the documentation or it's underway?

IMHO, I think it's enough to put examples in the future documentation, instead of raising an error. But I think we should perhaps put `blank=True` as a default, because `ListField` is by default an empty list. This will also tally with the default `Required=False` characteristic of the Django models.

What do you think?

Thanks for maintaining the framework though, you rock.

**Comment by last-partizan** [comment]
AFAIK django doesn't have `required` at all, that's mongoengine stuff.

so, i've added this little note: https://github.com/MongoEngine/django-mongoengine#fields-notes

**Comment by saraht129** [comment]
Ahh, you're right. `required=False` is the mongoengine's default for field. 

That note should do for now.

Thanks again!
