### ISSUE TITLE
Using ModelChoiceField with mongo queryset triggers AttributeError

### ISSUE THREAD

**Issue by saraht129** [MongoEngine/django-mongoengine#56]
Hi there,

I am trying to build a form with `ModelChoiceField`

`document = forms.ModelChoiceField(label="Document", queryset=Document.objects.all(), to_field_name="name")`

and I get `AttributeError`: `'QuerySet' object has no attribute '_prefetch_related_lookups'`.

Is this a known issue? I found on your code that you've done some functions mapping in `queryset.py`, is that suppose to address issue like this?

Please let me know what to look at to help with this issue, or is there anything I've not done right.

Thanks!

**Comment by last-partizan** [comment]
Yeah, queryset.py supposed to fix issues like this. Merging your pull-request.
