### ISSUE TITLE
How to login  a user using django-mongo-auth module

### ISSUE THREAD

**Issue by arima-sambunath** [MongoEngine/django-mongoengine#58]
code look like this

try:
        username = request.POST['username']
        print username
        pwd = request.POST['pwd']
        print pwd
        
      
       Please help to provide  rest of the code which authenticate user using 
                 django_mongoengine.mongo_auth.models import User 

        
        return redirect('/')
except DoesNotExist:
        return redirect('/')

**Comment by last-partizan** [comment]
Take a look at this.
https://docs.djangoproject.com/es/1.9/topics/auth/default/#how-to-log-a-user-in

with mongo everything should be exactly the same.

**Comment by arima-sambunath** [comment]
I think the above link perfect for  --  django.contrib.auth import authenticate, login (any relational db)
           
This code not working for django-mongoengine authentication

**Comment by last-partizan** [comment]
Are you added this lines to settings.py?

```
AUTH_USER_MODEL = 'mongo_auth.MongoUser'

AUTHENTICATION_BACKENDS = (
    'django_mongoengine.mongo_auth.backends.MongoEngineBackend',
)  
```


What error do you receive?

**Comment by arima-sambunath** [comment]
This is my settings.py

"""
Django settings for HealthReport project.

Generated by 'django-admin startproject' using Django 1.9.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import sys


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'i(sk_7s=w@m)=q=mi(91lw5@jy6tnphgll)iv0m)@&bam+grtz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# TEMPLATE_DEBUG = DEBUG

ADMINS = (
    ('admin', 'admin@gmail.com'),
)

MANAGERS = ADMINS
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_mongoengine',
    'django_mongoengine.mongo_auth',
    'django_mongoengine.mongo_admin.sites',
    'django_mongoengine.mongo_admin',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'HealthReport.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(os.path.join(BASE_DIR), 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



WSGI_APPLICATION = 'HealthReport.wsgi.application'


# MongoDB settings

MONGODB_DATABASES = {
    'default': {'name': 'healthreport_db'}
}



# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.dummy',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'mongo_auth.MongoUser'
AUTHENTICATION_BACKENDS = ('django_mongoengine.mongo_auth.backends.MongoEngineBackend')
SESSION_ENGINE = 'django_mongoengine.sessions'



# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_PATH = os.path.join(BASE_DIR,'staticfiles')

# PROJECT_ROOT = os.path.join(BASE_DIR,'query')

STATICFILES_DIRS = (
    STATIC_PATH,
)

STATIC_URL = '/static/'


# A sample logging configuration. The only tangible logging
# performed by this configuration is to send an email to
# the site admins on every HTTP 500 error when DEBUG=False.
# See http://docs.djangoproject.com/en/dev/topics/logging for
# more details on how to customize your logging configuration.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        }
    },
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler'
        }
    },
    'loggers': {
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': True,
        },
    }
}

**Comment by last-partizan** [comment]
```
AUTHENTICATION_BACKENDS = ('django_mongoengine.mongo_auth.backends.MongoEngineBackend')
```
there must be a comma after entry, like this

```
AUTHENTICATION_BACKENDS = ('django_mongoengine.mongo_auth.backends.MongoEngineBackend',)

```

**Comment by arima-sambunath** [comment]
Thank You So much !!!
            This really helpful to me 

is Django-mongoengine authorization (permission, group) works the same way like django authorization

**Comment by last-partizan** [comment]
It should work the same way, but i don't tested it. So check it yourself and report if something working not as expected.
