### ISSUE TITLE
Session Issue

### ISSUE THREAD

**Issue by waynetian** [MongoEngine/django-mongoengine#59]
if user login at first time without the session key, the session data will be overwrite by the SessionStore::save self._get_session(no_load=must_create).

so the user must re-login to give the correct session data

**Comment by last-partizan** [comment]
If user accessing site without session key, new session is created.

I don't understand what the problem is.
Can you provide steps to reproduce?

**Comment by waynetian** [comment]
OK, I find the issue in my two website projects. I use django-mongoengine as my session engine.


You can reproduce as the follows:


1. First (The most important!!!), confirm you access the site without session key.







2. Second. you can login your website with your name and password. 
The server side code is like this. It is easy to use django_maongoengine as session engine. If the session engine is correct, the session data will be save in the mongodb, but unlukily it is not. the account_id and username is missing.







I have traced the code, 





I reproduce the above steps, then the console will output as follows. You can see it has saved the session_data twice, and the last one is incorrect.







------------------ 原始邮件 ------------------
发件人: "last-partizan";<notifications@github.com>;
发送时间: 2016年5月11日(星期三) 晚上7:06
收件人: "MongoEngine/django-mongoengine"<django-mongoengine@noreply.github.com>; 
抄送: "WAYNE"<tianwei@vip.qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [MongoEngine/django-mongoengine] Session Issue (#59)




If user accessing site without session key, new session is created.
 
I don't understand what the problem is.
 Can you provide steps to reproduce?

**Comment by last-partizan** [comment]
I tried to reproduce your bug; Session indeed saved twice after login, but that is expected behavior; Django first created new session and then saves data after login.

![2016-05-11 15-28-54](https://cloud.githubusercontent.com/assets/301015/15180974/4955c7f8-178d-11e6-99ab-e85fbb96c5a1.png)

This is tested with our example/tumblelog app and login to django-admin.

`account_id` or `username` is not used by auth system, it uses `_auth_user_backend` and `_auth_user_id`.

**Comment by waynetian** [comment]
OK, I will make a simple reproduce steps. 

Step.1 Create a test view
```
class Test(TemplateView):
    def get(self, request, *args, **kwargs):
        test_data = request.session.get('test', None)
        print 'test=%s' %test_data
        request.session['test'] = 'abc123'
        return  HttpResponse('ok')
```
Step.2 Confirm your session key is None


Step.3 Access the View twice.
**Expected Result is:**
the first time: test=None
the second time: test='abc123'
**Actual Result is:**
the first time: test=None
the second time: test=None
the third time: test='abc123'

**Comment by last-partizan** [comment]
Nice, with your test case i confirmed bug.
Looks like it was issue with session caching. Fixed it myself. (your proposed fix was inapropriate)
