### ISSUE TITLE
http://docs.mongoengine.org/en/latest/django.html -- 404

### ISSUE THREAD

**Issue by pahaz** [MongoEngine/django-mongoengine#63]

**Comment by last-partizan** [comment]
Mongoengine does not include django integration, so there is no docs.

This project is not ready to production use yet.

**Comment by pahaz** [comment]
![image](https://cloud.githubusercontent.com/assets/1394025/16414815/525ade42-3d53-11e6-9705-ed3a201c485b.png)

Please change the description.

**Comment by last-partizan** [comment]
Updated.
