### ISSUE TITLE
MONGODB_DATABASES setting

### ISSUE THREAD

**Issue by ghost** [MongoEngine/django-mongoengine#7]
While still being undocumented, I found that your code does not necessarily adhere to both the mongoengine API (see django_mongoengine.utils.module where you will call register_connection), and to the conventions set forth by django for the settings.py.

The first requires the name parameter to be a positional argument rather than a keyword argument and the second requires that all keys are in upper case while the mongoengine API requires all keyword arguments in their lower case form.

My workaround for getting your dev branch (BTW why can I not just fetch and checkout that branch but instead have to pull for testing things out?), is as follows:

In the for loop near the end of the __init__ method of MongoEngine, I inserted the following code

            if 'NAME' not in conn_settings:
                raise ImproperlyConfigured("Missing `NAME` in %s connection settings" % (alias,))
            name = conn_settings['NAME']
            del conn_settings['NAME']
            effective_settings = {k.lower() : v for k, v in conn_settings.items()}
            self.connection.register_connection(alias, name, **effective_settings)

This got it up and running so far, without having tested any further except for getting the admin module up and running.

**Comment by last-partizan** [comment]
added MONGODB_DATABASES to readme, and i think it's better leave it as it is; we just use settings format which mongoengine accepts;
closing issue.
