### ISSUE TITLE
python manage.py createsupersuer fails

### ISSUE THREAD

**Issue by nesdis** [MongoEngine/django-mongoengine#74]
while trying to create a superuser, there is a failure.

Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\mongoengine\queryset\base.py", line 238, i
n get
    result = next(queryset)
  File "C:\Python35\lib\site-packages\mongoengine\queryset\base.py", line 1407,
in **next**
    raw_doc = next(self._cursor)
  File "C:\Python35\lib\site-packages\pymongo\cursor.py", line 1097, in next
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python35\lib\site-packages\django\core\management__init__.py", line
367, in execute_from_command_line
    utility.execute()
  File "C:\Python35\lib\site-packages\django\core\management__init__.py", line
359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python35\lib\site-packages\django\core\management\base.py", line 294,
 in run_from_argv
    self.execute(_args, *_cmd_options)
  File "C:\Python35\lib\site-packages\django\contrib\auth\management\commands\cr
eatesuperuser.py", line 63, in execute
    return super(Command, self).execute(_args, *_options)
  File "C:\Python35\lib\site-packages\django\core\management\base.py", line 345,
 in execute
    output = self.handle(_args, *_options)
  File "C:\Python35\lib\site-packages\django\contrib\auth\management\commands\cr
eatesuperuser.py", line 121, in handle
    self.UserModel._default_manager.db_manager(database).get_by_natural_key(user
name)
  File "C:\Python35\lib\site-packages\django\contrib\auth\base_user.py", line 48
, in get_by_natural_key
    return self.get(*_{self.model.USERNAME_FIELD: username})
  File "C:\Python35\lib\site-packages\django_mongoengine\mongo_auth\managers.py"
, line 72, in get
    return self.get_queryset().get(_args, **kwargs)
  File "C:\Python35\lib\site-packages\mongoengine\queryset\base.py", line 242, i
n get
    raise queryset._document.DoesNotExist(msg)
django_mongoengine.mongo_auth.models.DoesNotExist: User matching query does not
exist.

**Comment by last-partizan** [comment]
That's probably becouse django-mongoengine tries to do something not in the way django expects.

Unfortunately i don't have to investigate this now. If you need this - you can try to fix it yourlsef, or wait for someone else fixes (unlikely).

**Comment by chnpmy** [comment]
I met this problem too. Is this a bug in current version?

**Comment by last-partizan** [comment]
Yes, still not fixed.

**Comment by KiranPrajapati345** [comment]
ohhh.. that's why I always get errors.  :( ,

**Comment by last-partizan** [comment]
Yeah, probably nobody uses django-mongoengine as full replacement for mysql, so nobody fixed this yet(

**Comment by KiranPrajapati345** [comment]
Currently I have doing project. I want to connect mongodb with
django-rest-framework. I have data stored in mongodb databased( KIRAN  db).
Using django-rest framework i  want to show
my data. and create a complex queries . that's my task.

without mongo-engine I just load json file and create models.py ,
serializers.py  and everything works good in django-rest-frameworks. Please
see attachment . this output they want but using mongoengine.

But, my Boss say's " as long as data is stored in mongodb and not in mysql
with django".
so, last 5 days to I try to install mongoengine, and  every time I got error
so, there is another way using mongo database connect django-rest framework
and I complete my task ?


Thanks for replay.

Thanks and regards,
Kiran Prajapati

**Comment by last-partizan** [comment]
@KiranPrajapati345 take a look at https://github.com/umutbozkurt/django-rest-framework-mongoengine

And use mysql (or some other database) for django users/contenttypes, and mongoengine only for your app data.

**Comment by KiranPrajapati345** [comment]
I go through your link but it's not clear my doubts.

I  have so much doubts in "setting.py" file . I want to use "mongoengine"
for my database , to extract data from mongodb to create django-rest-api .

In above attachment I used database  engine  : 'django.db.backends.sqlite3'
so where I changed mongoengine.

If you have any example related to mongoengine will you please share with
me, it will be very helpful.

Thanks and regards,
Kiran Prajapati

**Comment by last-partizan** [comment]
https://github.com/MongoEngine/django-mongoengine/blob/master/example/tumblelog/tumblelog/settings.py#L18

here is our example project settings

you must use sqlite for DATABASES,
your mongo settings MONGODB_DATABASES
and do not use any of 
```
    'django_mongoengine.mongo_auth',
    'django_mongoengine.mongo_admin.sites',
    'django_mongoengine.mongo_admin',
```

just 'django_mongoengine' in INSTALLED_APPS

**Comment by KiranPrajapati345** [comment]
Okay ,
I will try and let you know.

Thank you so much..!!
You are awesome..!!

Thanks and regards,
Kiran Prajapati

**Comment by chnpmy** [comment]
I think I've fixed this bug  so that we can use command "python manage.py createmongodbsuperuser" to create a superuser for mongo use. I test it in my machine(python 3.5.2, django==1.10.5, mongoengine==0.11.0), the results are correct. But I can hardly write a unittest for it. Should I use make a pull request to merge with the code there? @last-partizan

**Comment by KiranPrajapati345** [comment]
oh. Wow. Thanks, I will check

Thanks,
Kiran

**Comment by last-partizan** [comment]
@chnpmy yeah, it would be nice

**Comment by chnpmy** [comment]
Thank you all  @KiranPrajapati345  @last-partizan . I've made the [request](https://github.com/MongoEngine/django-mongoengine/pull/84). please check it, thank you again.

**Comment by last-partizan** [comment]
Thanks, merged.
