### ISSUE TITLE
Erroneous imports in admin/options module

### ISSUE THREAD

**Issue by ghost** [MongoEngine/django-mongoengine#8]
I found out that when trying to activate your admin 'module' in my settings.py / INSTALLED_APPS, starting the embedded server will fail.

It turned out that one of the import statements referenced the wrong module for importing the LOOKUP_SEP constant.

Changing

from django.db.models.sql.constants import LOOKUP_SEP, QUERY_TERMS

to

from django.db.models.constants import LOOKUP_SEP
from django.db.models.sql.constants import QUERY_TERMS

made it actually compile and load so far.

**Comment by last-partizan** [comment]
It works in latest version of Django. Closing issue.
