### ISSUE TITLE
Pymongo Connection pool

### ISSUE THREAD

**Issue by ShipraShalini** [MongoEngine/django-mongoengine#86]
I would like to use connection pool in my django application using mongoengine.

I am unable to find anything in docs or any example for this .

I tried doing this:

```
MONGODB_DATABASES = {
    "default": {
        "name": MONGO_DB,
        "host": MONGO_URL,
        "username": MONGO_USER,
        "password": MONGO_PASSWORD,
        "minPoolSize": 200,
        "tz_aware": True, # if you using timezones in django (USE_TZ = True)
    }
}
```

The number of current connection did not increase.
I am using `db.serverStatus().connections` to check number of connections to mongo.

```
{
	"current" : 148,
	"available" : 51052,
	"totalCreated" : NumberLong(4087824)
}
```

I would really appreciate a sample example for this or using pymongo pool with django_mongoengine.

**Comment by last-partizan** [comment]
take a look at `mongoengine/connection.py`

we're using `register_connection` and it looks like it's passing kwargs like `minPoolSize` to `MongoClient` (in `get_connection`)

so, it probably must work (and i have no idea why it doesn't)

**Comment by ShipraShalini** [comment]
I tried to connect with mongoengine `connect` and it worked.

I will again try using `MONGODB_DATABASES` to check if I made any mistake, since  it's passing kwargs to   `MongoClient`. Closing the issue, will update if I find anything.
Thanks for your time and quick response.
