### ISSUE TITLE
'Required' option doesn't work

### ISSUE THREAD

**Issue by Deimos620** [MongoEngine/django-mongoengine#91]
I am using django_mongoengine.fields lib instead of mongoengine's one. But:
email = EmailField(max_length = MAX_LENGTH , required=false)
And , required=False works in mongoengine , but doesn't work in django.mongoengine.fields.
It always keep checking validation. I think this is small , but annoying bug.

**Comment by last-partizan** [comment]
from readme.md:

> Field(required=False), changed to django-style defaults -> Field(blank=False)

**Comment by Deimos620** [comment]
Ok. Thanks. This greatly helped me out!
