### ISSUE TITLE
Authentication doesn't work

### ISSUE THREAD

**Issue by Deimos620** [MongoEngine/django-mongoengine#92]
I am trying to implement authentication with DRF/django-Mongoengine.
I am trying to implement login API. But it seems session is not created when user log in first time.
request.session.session_key returns none , and , when I do request.session.save(),
then error occurs - 
"ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details."

I've set main db engine as dummy , and connected db with django-mongoengine.

It seems , Django tries to create session db and failed because main db engine is dummy.
Would you like to help me how to solve this?
Here is what I have done for login.

        if user.is_active:
            if user.check_password(password):
                login(request)
                token = csrf._get_new_csrf_key()
                if not request.session.session_key:
                    request.session.save()
                response = Response({"success": "Login Succeeded", "key": settings.SECRET_KEY},
                                status=status.HTTP_200_OK)
                # Set Cookie / header
                response.__setitem__('X-CSRFToken', token)
                response.set_cookie('username', user.username, max_age=MAX_AGE)
                response.set_cookie('userid', user.id, max_age=MAX_AGE)

PS: I can not save cookie  - from the issue session is None.

**Comment by last-partizan** [comment]
Try changing DATABASES to something django will like, if it doesn't help - check SESSION_ENGINE
