### ISSUE TITLE
Authentiation doesn't work(2)

### ISSUE THREAD

**Issue by Deimos620** [MongoEngine/django-mongoengine#93]
Hi @last-partizan 

How are you?
While keep trying to do authenticate with django-mongoengine , I have found another issue.

I have configured db as dummy.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.dummy',
        'NAME':''
    }
}
And connected mongodb with django-mongoengine.

MONGODB_DATABASES = {
    "default": {
        "name": MONGO_DBNAME,
        "host": MONGO_SERVER,
        "password": MONGO_PASS,
        "username": MONGO_USER,
        "tz_aware": True, # if you using timezones in django (USE_TZ = True)
    },
}

I could implement login itself , but while call another api , got the issue like below.

ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.

I see this is occured before , And is there a way to use mongodb instead of sqldb - sqlite or mysql for django / django rest framework?

**Comment by last-partizan** [comment]
Hi, i'm not tested combination with DRF, it may work if you don't touch serialization, or maybe even with it if youre lucky.
To fix your trace just change DATABASES for something django will like. And use mongo where you need it.

**Comment by Deimos620** [comment]
Dear @last-partizan ,

So , It means, I should use two databases - sql db for authentication , and mongodb  for where I need- right? This app is already built with django 1.9 , and using sqlite l for user registration / authentication , and mongodb for other stuffs. I want to use only one database - I think using two db in one app is not good practice. But If you don't think this issue will be fixed soon , then I will use traditional sql db for django based user authentication.

**Comment by last-partizan** [comment]
Probably yes, you should use two databases. It's some django stuff that requires DATABASES.
Maybe take a look at example app, i don't remember if it works with only one.

**Comment by Deimos620** [comment]
Ok. I got it. Thanks for your help , @last-partizan.
