### ISSUE TITLE
'ObjectIdField' object has no attribute 'verbose_name'

### ISSUE THREAD

**Issue by Vayel** [MongoEngine/django-mongoengine#95]
Hi!

I try to use Django Swagger and it raises an error:

```
'ObjectIdField' object has no attribute 'verbose_name'

File "/home/vincent/.local/share/virtualenvs/ieml/lib/python3.6/site-packages/rest_framework/schemas.py" in get_path_fields
  539.                 if model_field is not None and model_field.verbose_name:
```

It is probably due to the fact that, contrary to other [field classes](https://github.com/MongoEngine/django-mongoengine/blob/master/django_mongoengine/fields/djangoflavor.py), `ObjectIdField` does not inherit from `DjangoField`.

**Comment by last-partizan** [comment]
Probably, yes and I don't remember why. 

Take a look at `fields/__init__.py` `patch_mongoengine_field` and try to add `verbose_name` as property

**Comment by Vayel** [comment]
Thanks for your response. I tried what you suggested, but I obtain an error:

```python
# fields.__init__.py

def patch_mongoengine_field(field_name):
    """
    patch mongoengine.[field_name] for comparison support
    because it's required in django.forms.models.fields_for_model
    importing using mongoengine internal import cache
    """
    from mongoengine import common
    field = common._import_class(field_name)
    for k in ["__eq__", "__lt__", "__hash__", "attname", "verbose_name", "help_text",]:  # I added two attributes
        if not k in field.__dict__:
            setattr(field, k, djangoflavor.DjangoField.__dict__[k])

# fields/djangoflavor.py

class DjangoField(object):

    verbose_name = None
    help_text = None
```

An the error:

```python
# ...
File "/home/vincent/.local/share/virtualenvs/ieml/lib/python3.6/site-packages/django_mongoengine-0.2.1-py3.6.egg/django_mongoengine/fields/djangoflavor.py", line 29, in __init__
    super(DjangoField, self).__init__(*args, **kwargs)
  File "/home/vincent/.local/share/virtualenvs/ieml/lib/python3.6/site-packages/mongoengine/fields.py", line 67, in __init__
    super(StringField, self).__init__(**kwargs)
  File "/home/vincent/.local/share/virtualenvs/ieml/lib/python3.6/site-packages/mongoengine/base/fields.py", line 99, in __init__
    self.__class__.__name__, ', '.join(conflicts)))
TypeError: StringField already has attribute(s): verbose_name
```

It is due to the fact that `StringField` is patched and inherit from `DjangoField`.

I can simply do:

```python
# fields/__init__.py

from mongoengine import common
field = common._import_class("ObjectIdField")
setattr(field, "verbose_name", None)
setattr(field, "help_text", None)

# fields/djangoflavor.py

class DjangoField(object):

    get_choices = Field.__dict__["get_choices"]

    def __init__(self, *args, **kwargs):
        # ...
```

And Django Swagger works quite well. But I am not sure it is the cleanest way to do.

**Comment by last-partizan** [comment]
Check branch `95_fix-swagger`

https://github.com/MongoEngine/django-mongoengine/commit/dab0857550280e46f248988d82f958423ef20723

i tried to patch every class in mongoengine import cache, maybe it will work

**Comment by Vayel** [comment]
@last-partizan Unfortunately, I get the same error:

```
AttributeError at /api
'ObjectIdField' object has no attribute 'verbose_name'
```

**Comment by last-partizan** [comment]
DjangoField sets verbose_name on init (just like it's django variant)

**Comment by Vayel** [comment]
Ok, there is the problem:

```python
# django_mongoengine/fields/__init__.py

# ...
init_module()
print(ObjectIdField()) # <django_mongoengine.fields.ObjectIdField object at 0x7f01d86de860>

# rest_framework/schemas.py:539

print(model_field) # <mongoengine.base.fields.ObjectIdField object at 0x7f8527f52518>
```

I assume that Django Rest Framework Mongoengine does not use Django Mongoengine fields. @BurkovBA do you think it is possible to fix it?

**Comment by BurkovBA** [comment]
@last-partizan 
Здрав будь, боярин!

@Vayel 
Indeed, we're not using Django-Mongoengine fields currently. I wonder, how this django-mongoengine integration machinery works alltogether? There's a django-mongodb-engine project, which was an attempt to make a proper MongoDB Django backend. Being 90% compatible with Django ORM Models and Queryset API, Mongoengine at the same time is not a first-class Django citizen. And this is by design - it was not meant for use with Django only - e.g. Flask guys make use of it, too. I wonder, what's the approach of Django-Mongoengine to integrate Mongoengine with Django models and stuff?

**Comment by last-partizan** [comment]
django-mongoengine works by some magick and monkey-patching, and by the looks of it that does not works very well every time

@Vayel probably you can monkey-patch it in your app, but i don't think it's a good idea

django-mongoengine looks dead by now. and if i was choosing what to use today - i'd take something like mongoengine (or motor)
