### ISSUE TITLE
Attribute error on Django 1.8.x

### ISSUE THREAD

**Issue by apolkosnik** [MongoEngine/django-mongoengine#97]
File "/usr/local/lib/python2.7/site-packages/django_mongoengine/document.py", line 8, in <module>
    from .forms.document_options import DocumentMetaWrapper
  File "/usr/local/lib/python2.7/site-packages/django_mongoengine/forms/document_options.py", line 45, in <module>
    class DocumentMetaWrapper(object):
  File "/usr/local/lib/python2.7/site-packages/django_mongoengine/forms/document_options.py", line 68, in DocumentMetaWrapper
    default_apps = Options.default_apps
AttributeError: type object 'Options' has no attribute 'default_apps'

**Comment by last-partizan** [comment]
We don't support django 1.8 at the moment, but you can fix it if you need it.

After fixes, run this tests and create pull request.
https://github.com/MongoEngine/django-mongoengine#how-to-run-tests

**Comment by apolkosnik** [comment]
I've added the following, I think that it should do it for 1.8:
    try:
        default_apps = Options.default_apps
    except AttributeError:
        pass

**Comment by last-partizan** [comment]
Not really, it just breaks in different place.

run tests and check it yourself.

**Comment by apolkosnik** [comment]
I ran tests, and it looks ok on Django 1.8.
https://github.com/MongoEngine/django-mongoengine/pull/98

**Comment by apolkosnik** [comment]
Thanks!
