### ISSUE TITLE
type object 'Options' has no attribute 'default_apps'  (python 3.6.1,django 1.9.2)

### ISSUE THREAD

**Issue by ghotiv** [MongoEngine/django-mongoengine#99]
python 3.6.1,django 1.9.2

import django_mongoengine

..../site-packages/django_mongoengine-0.2.1-py3.6.egg/django_mongoengine/forms/document_options.py", line 68, in DocumentMetaWrapper
    default_apps = Options.default_apps
AttributeError: type object 'Options' has no attribute 'default_apps'

django 1.11.2 works fine

**Comment by last-partizan** [comment]
try latest version from git, it must be fixed already
